# Generated by Django 2.1.3 on 2018-11-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'managed': True},
        ),
    ]
