# Generated by Django 2.1.3 on 2018-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0002_auto_20181122_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
